spring: 
 datasource: 
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://10.99.39.211:3306/my_test?useUnicode=true&characterEncoding=utf-8
  username: mysql
  password: mysql